--- #YAML:1.0
name:               WebService-EastCoJp-Dictionary
version:            0.02
abstract:           An interface for REST service of EAST.co.jp
author:
    - Kuniyoshi Kouji <kuniyoshi@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Modern::Perl:      0
    Moose:             0
    Readonly:          1.03
    Test::LongString:  0.11
    URI::Escape:       0
    XML::XPath:        1.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
